DROP TABLE IF EXISTS PUBLIC.CLIENT;

CREATE TABLE PUBLIC.CLIENT (
  ID          INTEGER      NOT NULL AUTO_INCREMENT,
  FIRST_NAME  VARCHAR(255) NOT NULL,
  SECOND_NAME VARCHAR(255) NOT NULL,
  CONSTRAINT AUTHOR_PRIMARY_KEY PRIMARY KEY (ID),
);

DROP TABLE IF EXISTS PUBLIC.LOAN;

CREATE TABLE PUBLIC.LOAN (
  ID           INTEGER          NOT NULL AUTO_INCREMENT,
  TERM_START   DATE             NOT NULL,
  TERM_END     DATE             NOT NULL,
  AMOUNT       DECIMAL          NOT NULL,
  CURRENCY     VARCHAR(55)      NOT NULL,
  UPDATED_DATE TIMESTAMP        NOT NULL,
  CREATED_DATE TIMESTAMP        NOT NULL,
  STATUS       ENUM('ACTIVE',
                    'EXTENDED',
                    'CLOSED')   NOT NULL,
  CLIENT_ID    INTEGER          NOT NULL,
  CONSTRAINT LOAN_PRIMARY_KEY PRIMARY KEY (ID),
  CONSTRAINT CLIENT_FOREIGN_KEY FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);

INSERT INTO PUBLIC.CLIENT (FIRST_NAME, SECOND_NAME)
VALUES ('John', 'Snow'),
       ('NotEnough', 'Time');
